"""Unit tests for foveaedge.model — ModelLoader, ModelInfo, TensorInfo."""

from __future__ import annotations

from pathlib import Path

import pytest

from foveaedge.model import ModelInfo, ModelLoader, TensorInfo

# Path to the test model generated by models/generate_test_model.py
TEST_MODEL_DIR = Path(__file__).resolve().parent.parent.parent / "models" / "test_model"
TEST_MODEL_XML = TEST_MODEL_DIR / "test_model.xml"
TEST_MODEL_ONNX = TEST_MODEL_DIR / "test_model.onnx"


# ---------------------------------------------------------------------------
# TensorInfo tests
# ---------------------------------------------------------------------------


class TestTensorInfo:
    """Tests for TensorInfo dataclass."""

    def test_creation(self):
        """TensorInfo stores name, shape, element_type."""
        t = TensorInfo(name="input", shape=(1, 3, 32, 32), element_type="f32")
        assert t.name == "input"
        assert t.shape == (1, 3, 32, 32)
        assert t.element_type == "f32"

    def test_layout_default(self):
        """TensorInfo layout defaults to empty string."""
        t = TensorInfo(name="x", shape=(1, 10), element_type="f32")
        assert t.layout == ""

    def test_frozen(self):
        """TensorInfo is frozen (immutable)."""
        t = TensorInfo(name="x", shape=(1,), element_type="f32")
        with pytest.raises(AttributeError):
            t.name = "y"  # type: ignore[misc]

    def test_repr(self):
        """TensorInfo repr includes name, shape, type."""
        t = TensorInfo(name="input", shape=(1, 3, 32, 32), element_type="f32")
        r = repr(t)
        assert "input" in r
        assert "(1, 3, 32, 32)" in r
        assert "f32" in r


# ---------------------------------------------------------------------------
# ModelInfo tests
# ---------------------------------------------------------------------------


class TestModelInfo:
    """Tests for ModelInfo dataclass."""

    def test_creation(self):
        """ModelInfo stores path, name, tensors, device."""
        info = ModelInfo(
            model_path="/path/to/model.xml",
            model_name="model",
            input_tensors=[TensorInfo("in", (1, 3), "f32")],
            output_tensors=[TensorInfo("out", (1, 10), "f32")],
            requested_device="CPU",
        )
        assert info.model_path == "/path/to/model.xml"
        assert info.model_name == "model"
        assert len(info.input_tensors) == 1
        assert len(info.output_tensors) == 1

    def test_input_names(self):
        """ModelInfo.input_names returns list of input tensor names."""
        info = ModelInfo(
            model_path="m.xml",
            model_name="m",
            input_tensors=[
                TensorInfo("a", (1,), "f32"),
                TensorInfo("b", (1,), "f32"),
            ],
        )
        assert info.input_names == ["a", "b"]

    def test_output_names(self):
        """ModelInfo.output_names returns list of output tensor names."""
        info = ModelInfo(
            model_path="m.xml",
            model_name="m",
            output_tensors=[TensorInfo("out", (1, 10), "f32")],
        )
        assert info.output_names == ["out"]

    def test_input_shapes(self):
        """ModelInfo.input_shapes returns list of shape tuples."""
        info = ModelInfo(
            model_path="m.xml",
            model_name="m",
            input_tensors=[TensorInfo("in", (1, 3, 224, 224), "f32")],
        )
        assert info.input_shapes == [(1, 3, 224, 224)]

    def test_output_shapes(self):
        """ModelInfo.output_shapes returns list of shape tuples."""
        info = ModelInfo(
            model_path="m.xml",
            model_name="m",
            output_tensors=[TensorInfo("out", (1, 1000), "f32")],
        )
        assert info.output_shapes == [(1, 1000)]

    def test_defaults(self):
        """ModelInfo defaults to empty lists for tensors."""
        info = ModelInfo(model_path="m.xml", model_name="m")
        assert info.input_tensors == []
        assert info.output_tensors == []
        assert info.requested_device == ""
        assert info.compiled_device == ""

    def test_frozen(self):
        """ModelInfo is frozen (immutable)."""
        info = ModelInfo(model_path="m.xml", model_name="m")
        with pytest.raises(AttributeError):
            info.model_name = "x"  # type: ignore[misc]

    def test_repr(self):
        """ModelInfo repr includes name and counts."""
        info = ModelInfo(
            model_path="m.xml",
            model_name="m",
            input_tensors=[TensorInfo("in", (1,), "f32")],
            output_tensors=[TensorInfo("out", (1,), "f32")],
            compiled_device="CPU",
        )
        r = repr(info)
        assert "m" in r
        assert "CPU" in r


# ---------------------------------------------------------------------------
# ModelLoader tests
# ---------------------------------------------------------------------------


class TestModelLoader:
    """Tests for ModelLoader class."""

    def test_init(self):
        """ModelLoader initializes with OpenVINO Core."""
        loader = ModelLoader()
        assert loader.core is not None
        assert loader.model is None
        assert loader.compiled_model is None
        assert loader.model_info is None

    def test_available_devices(self):
        """ModelLoader returns at least CPU device."""
        loader = ModelLoader()
        devices = loader.available_devices()
        assert isinstance(devices, list)
        assert "CPU" in devices

    def test_validate_device_valid(self):
        """validate_device returns True for CPU."""
        loader = ModelLoader()
        assert loader.validate_device("CPU") is True

    def test_validate_device_invalid(self):
        """validate_device returns False for nonexistent device."""
        loader = ModelLoader()
        assert loader.validate_device("NONEXISTENT_DEVICE") is False

    def test_load_valid_model(self):
        """load() returns ModelInfo for a valid model."""
        if not TEST_MODEL_XML.exists():
            pytest.skip("Test model not generated")
        loader = ModelLoader()
        info = loader.load(str(TEST_MODEL_XML), device="CPU")
        assert isinstance(info, ModelInfo)
        assert info.model_name == "test_model"
        assert len(info.input_tensors) > 0
        assert len(info.output_tensors) > 0
        assert info.requested_device == "CPU"

    def test_load_onnx_model(self):
        """load() works with ONNX format."""
        if not TEST_MODEL_ONNX.exists():
            pytest.skip("Test ONNX model not generated")
        loader = ModelLoader()
        info = loader.load(str(TEST_MODEL_ONNX), device="CPU")
        assert isinstance(info, ModelInfo)
        assert len(info.input_tensors) > 0

    def test_load_invalid_path(self):
        """load() raises FileNotFoundError for nonexistent path."""
        loader = ModelLoader()
        with pytest.raises(FileNotFoundError, match="not found"):
            loader.load("nonexistent_model.xml")

    def test_load_invalid_device(self):
        """load() raises RuntimeError for unavailable device."""
        if not TEST_MODEL_XML.exists():
            pytest.skip("Test model not generated")
        loader = ModelLoader()
        with pytest.raises(RuntimeError, match="not available"):
            loader.load(str(TEST_MODEL_XML), device="NONEXISTENT_DEVICE")

    def test_compile(self):
        """compile() returns a compiled model."""
        if not TEST_MODEL_XML.exists():
            pytest.skip("Test model not generated")
        loader = ModelLoader()
        loader.load(str(TEST_MODEL_XML), device="CPU")
        compiled = loader.compile()
        assert compiled is not None

    def test_compile_updates_info(self):
        """compile() updates model_info with compiled_device."""
        if not TEST_MODEL_XML.exists():
            pytest.skip("Test model not generated")
        loader = ModelLoader()
        info = loader.load(str(TEST_MODEL_XML), device="CPU")
        assert info.compiled_device == ""
        loader.compile()
        assert loader.model_info.compiled_device == "CPU"

    def test_compile_without_load(self):
        """compile() raises RuntimeError if no model loaded."""
        loader = ModelLoader()
        with pytest.raises(RuntimeError, match="No model loaded"):
            loader.compile()

    def test_compile_invalid_device(self):
        """compile() raises RuntimeError for unavailable device."""
        if not TEST_MODEL_XML.exists():
            pytest.skip("Test model not generated")
        loader = ModelLoader()
        loader.load(str(TEST_MODEL_XML), device="CPU")
        with pytest.raises(RuntimeError, match="not available"):
            loader.compile(device="NONEXISTENT_DEVICE")

    def test_load_and_compile(self):
        """load_and_compile() loads and compiles in one step."""
        if not TEST_MODEL_XML.exists():
            pytest.skip("Test model not generated")
        loader = ModelLoader()
        info = loader.load_and_compile(str(TEST_MODEL_XML), device="CPU")
        assert isinstance(info, ModelInfo)
        assert info.compiled_device == "CPU"
        assert loader.compiled_model is not None

    def test_input_metadata(self):
        """ModelLoader extracts correct input metadata."""
        if not TEST_MODEL_XML.exists():
            pytest.skip("Test model not generated")
        loader = ModelLoader()
        info = loader.load_and_compile(str(TEST_MODEL_XML), device="CPU")
        assert info.input_tensors[0].name == "input"
        assert tuple(info.input_tensors[0].shape) == (1, 3, 32, 32)

    def test_output_metadata(self):
        """ModelLoader extracts correct output metadata."""
        if not TEST_MODEL_XML.exists():
            pytest.skip("Test model not generated")
        loader = ModelLoader()
        info = loader.load_and_compile(str(TEST_MODEL_XML), device="CPU")
        assert len(info.output_tensors) == 1
        assert tuple(info.output_tensors[0].shape) == (1, 10)
